### ISSUE TITLE
README.md に、今日の朝食を表示できる

### ISSUE THREAD

**Issue by ghost** [gits-takaoka/first-sample#1]
## Why

以下の開発フローを実施できるようになりたい
- 作業開始の起点となるIssue を発行する
- 発行されたIssue番号をもとに、ブランチを作成する
- ブランチ内で ファイルを編集し、git commit する
- git commit した ブランチを git push する
- git push したブランチを、masterブランチにマージするPull Request を作成する
- 作成したPullRequestのレビューを依頼する
- 作成したPullRequestがマージされる、つまり、master ブランチにマージされる

## What

- #1 の issue を作成した
- GitKraken で、`#1-readme` ブランチを作成する
- `#1-readme` ブランチ で、README.md ファイルを編集し、git commit する
- `#1-readme` ブランチ を GitKraken で、push する　
　github 上で、`#1-readme` ブランチ　がpushされたことを確認する
- `#1-readme` ブランチ を master ブランチにマージするための PullRequest を作成する

**Comment by ghost** [comment]
PRが、mergeされる前に、issue を closeしてはいけません。。
PRを merge しない、する必要がないなら、issue を close してもよいですが。。

**Comment by ghost** [comment]
残念なががら、私に権限がないようなので、この issue を re open できません。。

**Comment by gits-takaoka** [comment]
操作間違えたようで、すいません。

**Comment by ghost** [comment]
done
